<a href="https://colab.research.google.com/github/eunji32/TIL/blob/main/basic_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**<<< 메모 >>>**
1. 인덴트 = 들여쓰기
2. 불리언 : 0은 false / 0이 아닌 숫자나 문자 모드 true
* True(사실,1) / False(거짓,0)



In [1]:
str_data = '시작은 0부터'

In [2]:
str_data[0]

'시'

In [3]:
# 공백도 인덱스
str_data[3]

' '

In [4]:
str_data[-1]

'터'

In [5]:
num = 1234

In [6]:
type(str_data)

str

In [7]:
type(num)

int

In [8]:
bool(1)

True

In [9]:
bool(0.0)

False

In [10]:
bool(0)

False

In [11]:
bool(3)

True

In [12]:
bool('안녕하세요')

True

In [13]:
# 부동소수점(float)표현하기
# 문자 e사용 - ex) 1억표현하기
1e8

100000000.0

In [14]:
type(1e8)

float

In [15]:
# 0.000123
123.e-6

0.000123

In [16]:
"""merry
christmas"""

'merry\nchristmas'

**튜플 ()**

In [17]:
# 데이터를 수정/추가/삭제 불가
산 = ('한라산','지리산','설악산','도봉산')
산

('한라산', '지리산', '설악산', '도봉산')

In [18]:
type(산)

tuple

In [19]:
산[1]

'지리산'

In [20]:
산[-3]

'지리산'

**리스트 []**

In [21]:
# 수정/삭제 등이 매우 쉬움
산 = ['한라산','지리산','설악산','도봉산']
산

['한라산', '지리산', '설악산', '도봉산']

In [22]:
type(산)

list

In [23]:
산[2]

'설악산'

In [24]:
# 리스트는 연결된 데이터 중 일부만 추출가능. [시작:원하는마지막위치+1]
산[1:3]

['지리산', '설악산']

In [25]:
산[-4]

'한라산'

In [26]:
산+산

['한라산', '지리산', '설악산', '도봉산', '한라산', '지리산', '설악산', '도봉산']

In [27]:
# 단, 뺄셈과 나눗셈은 리스트에서 수행되지 않음.
산*3

['한라산',
 '지리산',
 '설악산',
 '도봉산',
 '한라산',
 '지리산',
 '설악산',
 '도봉산',
 '한라산',
 '지리산',
 '설악산',
 '도봉산']

In [28]:
# 리스트 데이터 변경
산[2] = '설악산2'
산

['한라산', '지리산', '설악산2', '도봉산']

In [29]:
# 리스트 데이터 삭제 
# del : 인덱스로 삭제
del 산[2]
산

['한라산', '지리산', '도봉산']

In [30]:
# append() : 맨뒤에 데이터 추가 , 튜플과 리스트가 동일하게 지닌 특성
# 기존에 동일한 데이터가 있어도 추가로 중복된 데이터 추가 가능.
산.append('태백산')
산

['한라산', '지리산', '도봉산', '태백산']

In [31]:
# insert() : 원하는 위치에 데이터 끼워넣기 
# 2번위치에 설악산
산.insert(2,'설악산')
산.insert(0,'태백산')
산

['태백산', '한라산', '지리산', '설악산', '도봉산', '태백산']

In [32]:
# count() : 값 개수
산.count('태백산')

2

In [33]:
# remove() : 값 삭제
# 값 중 가장 앞에 위치한 '태백산'값만 삭제됨.
산.remove('태백산')
산

['한라산', '지리산', '설악산', '도봉산', '태백산']

In [34]:
# pop() : 값 삭제
# 마지막에 있는 값 우선 삭제
산.pop()
산

['한라산', '지리산', '설악산', '도봉산']

In [35]:
# sort() : 정렬, 오름차순정렬
# 정렬함과 동시에 변숫값에 즉시 반영됨으로 주의!!
산.sort()
산

['도봉산', '설악산', '지리산', '한라산']

In [36]:
# sort() : 내림차순
산.sort(reverse=True)
산

['한라산', '지리산', '설악산', '도봉산']

In [37]:
# sort(key = ) : key 옵션에 지정된 함수의 결과에따라 정렬
m = '난 파이썬을 잘하고 싶다'
m = m.split()
m

['난', '파이썬을', '잘하고', '싶다']

In [38]:
m.sort(key=len) # 원소길이에 따라 정렬
m

['난', '싶다', '잘하고', '파이썬을']

In [39]:
# 본체에 영향을 주지 않는 정렬
# sorted() : 순서대로 정렬, 정렬된 리스트를 반환
x = [1 ,11, 2, 3]
y = sorted(x)
x

[1, 11, 2, 3]

In [40]:
y

[1, 2, 3, 11]

In [41]:
# reversed : 거꾸로 뒤집기, iterable한 객체를 반환, 확인을 위해서는 list로 한번 더 변형 필요
x = [1 ,11, 2, 3]
y = reversed(x)
x

[1, 11, 2, 3]

In [42]:
y

In [43]:
list(y)

[3, 2, 11, 1]

**딕셔너리{}**

In [44]:
# 찾고 싶은 단어(key)를 사전에서 찾은후 그 의미(값)을 이해하는 방식
# 키를 통해서 원하는 값을 얻음.
산 = {'1등높이':'한라산',
     '2등높이':'지리산',
     '3등높이':'설악산',
     '4등높이':'덕유산'
     }

산

{'1등높이': '한라산', '2등높이': '지리산', '3등높이': '설악산', '4등높이': '덕유산'}

In [45]:
type(산)

dict

In [46]:
# 특정한 값에 접근 시 []사용
산['2등높이']

'지리산'

In [47]:
# 새로운 딕셔너리 쌍 만들기
산['5등높이'] = '태백산'
산

{'1등높이': '한라산', '2등높이': '지리산', '3등높이': '설악산', '4등높이': '덕유산', '5등높이': '태백산'}

In [48]:
# 동일한 키가 존재하는 경우 마지막 추가된 키:값이 살아남음.
산['5등높이'] = '오대산'
산

{'1등높이': '한라산', '2등높이': '지리산', '3등높이': '설악산', '4등높이': '덕유산', '5등높이': '오대산'}

In [49]:
산['5등높이']  = '계방산'
산['1등높이'] = '제주한라산'
산

{'1등높이': '제주한라산', '2등높이': '지리산', '3등높이': '설악산', '4등높이': '덕유산', '5등높이': '계방산'}

In [50]:
# 딕셔너리 삭제
del 산['2등높이']
del 산['4등높이']
del 산['5등높이']

산

{'1등높이': '제주한라산', '3등높이': '설악산'}

In [51]:
# 데이터 추가
산['2등높이'] = '지리산'
산

{'1등높이': '제주한라산', '2등높이': '지리산', '3등높이': '설악산'}

**집합 set()**

In [52]:
# 중복된 데이터가 없고, 데이터 간 순서가 없다.
# 집합생성 방법2가지
# 1번째
헬로우 = set("hello")
헬로우

{'e', 'h', 'l', 'o'}

In [53]:
# 2번째
하이 = set(['h','i'])
하이

{'h', 'i'}

In [54]:
# intersection() : 교집합 연산
헬로우.intersection(하이)

{'h'}

In [55]:
# 교집합 연산자
헬로우&하이 

{'h'}

In [56]:
# union() : 합집합
헬로우.union(하이)

{'e', 'h', 'i', 'l', 'o'}

In [57]:
# 합집합 연산자
헬로우|하이

{'e', 'h', 'i', 'l', 'o'}

In [58]:
# difference() : 차집합
헬로우.difference(하이)

{'e', 'l', 'o'}

In [59]:
# 차집합 연산자
헬로우-하이

{'e', 'l', 'o'}

In [60]:
# 차집합은 무엇을 기준으로 하느냐에 따라 결과가 달라짐
하이-헬로우

{'i'}

In [61]:
# add() : 하나의 원소추가
# update() : 여러 개의 원소를 한꺼번에 추가
# remove() : 특정 원소 삭제
헬로우.add('!')
헬로우

{'!', 'e', 'h', 'l', 'o'}

In [62]:
헬로우.update(['w','o','w'])
헬로우

{'!', 'e', 'h', 'l', 'o', 'w'}

In [63]:
헬로우.remove('!')
헬로우

{'e', 'h', 'l', 'o', 'w'}

**연산자**

In [64]:
# 산술연산자
2/5

0.4

In [65]:
2//5 # 몫

0

In [66]:
2%5 # 나머지

2

In [67]:
2**5 # 거듭제곱

32

In [68]:
파이썬점수 = 90
빅데이터점수 = 70

In [69]:
# AND연산자(교집합)
# 둘다 맞다 : T  그외 F
(파이썬점수 > 80) and (빅데이터점수 >80)

False

In [70]:
(파이썬점수 > 80) and (빅데이터점수 > 60)

True

In [71]:
# OR연산자(합집합)
# 둘 중 하나라도 맞으면 T
(파이썬점수 > 80) or (빅데이터점수 >80)

True

In [72]:
(파이썬점수 > 90) and (빅데이터점수 >90)

False

In [73]:
# NOT연산자(여집합)
# 오른쪽이 틀림 T / 맞으면 F
not (파이썬점수 > 90)

True

In [74]:
not (파이썬점수 > 80)

False

**문자열 가공**

In [75]:
# 문자열 결합
# +로 결합 : 공백 포함
'I '+'AM '+'SUPERMAN!'

'I AM SUPERMAN!'

In [76]:
# 변수에 담아 결합
나 = 'I '
는 = 'AM '
슈퍼맨 = 'SUPERMAN!'
나+는+슈퍼맨

'I AM SUPERMAN!'

In [77]:
# 끼어들 변수.JOIN(끼어들 대상)
'-'.join('superman!')

's-u-p-e-r-m-a-n-!'

In [78]:
끼어들변수 = '*'
끼어들대상 = 'ABCD'
끼어들변수.join(끼어들대상)

'A*B*C*D'

In [79]:
# 문자열 복제
'A' *5

'AAAAA'

In [80]:
# 문자추출 - 하나의 특정문자
문자열 = 'ABCDEFG'
문자열[4]

'E'

In [81]:
문자열[-3]

'E'

In [82]:
# 문자 추출(슬라이싱) - 일부의 문자열
# 문자열[시작위치:끝위치:건너뛰기 수]
# 만약 시작위치를 작성하지 않으면 문자열의 맨처음부터 가져옴.(끝위치도 마찬가지)
# 끝위치는 입력된 끝위치의 이전 값까지 데이터 추출
문자열[2:5]

'CDE'

In [83]:
문자열[::2]

'ACEG'

In [84]:
문자열[4::-2]

'ECA'

In [85]:
문자열[6:2:-3]

'GD'

In [86]:
# len() :  문자열 길이재기
len('abcd')

4

In [87]:
len(문자열)

7

In [88]:
# split() : 문자열 분리
# 문자열/변수.split('구분자')
# 리스트에 반환됨.
슈퍼맨 = 'i am superman!'
슈퍼맨.split(' ')

['i', 'am', 'superman!']

In [89]:
'a-b-c-d'.split('-')

['a', 'b', 'c', 'd']

In [90]:
# replace() : 문자열 교체
# 문자열/변수.replace('변경전단어','변경후단어')
슈퍼맨.replace('superman','batman')

'i am batman!'

In [91]:
# find(),index() : 문자열 위치찾기
# 문자열/변수.find('찾을단어)
애국가 = '''동해물과 백두산이 마르고 닳도록
하느님이 보우하사 우리나라 만세
무궁화 삼천리 화려 강산
대한 사람 대한으로 길이 보전하세'''
애국가

'동해물과 백두산이 마르고 닳도록\n하느님이 보우하사 우리나라 만세\n무궁화 삼천리 화려 강산\n대한 사람 대한으로 길이 보전하세'

In [92]:
애국가.find('우리나라')

28

In [93]:
애국가.index('우리나라')

28

In [94]:
# 찾는단어가 없으면 find는 -1 / index는 오류
애국가.find('한라산')

-1

In [95]:
#애국가.index('한라산') # index는 오류

In [96]:
# count() : 문자열 개수 
# 문자열/변수.count('카운트할단어)
애국가.count('대한')

2

In [97]:
# capitalize() : 첫단어의 첫문자만 대문자! 나머지는 소문자!
# title() : 각 단어의 첫문자를 대문자로! 나머지는 소문자!
슈퍼맨 = 'i aM SuperMan!'
슈퍼맨

'i aM SuperMan!'

In [98]:
슈퍼맨.capitalize()

'I am superman!'

In [99]:
슈퍼맨.title()

'I Am Superman!'

In [100]:
# upper() : 모두 대문자
# lower() : 모두 소문자
슈퍼맨.upper()

'I AM SUPERMAN!'

In [101]:
슈퍼맨.lower()

'i am superman!'

**if**

In [102]:
평균점수 = 72
if 평균점수 >=90:
  print('A학점')
  print('야호!')
elif 평균점수 >= 80:
  print('B학점')
  print('분발하자')
elif 평균점수 >= 70:
  print('C학점')
  print('공부하자')
else:
  print('D학점')
  print('할 말 없음')


C학점
공부하자


for

In [103]:
과목 = ['국어','수학','역사','영어']
for 한개씩 in 과목:
  print(한개씩)

국어
수학
역사
영어


In [104]:
for 한개씩 in 과목 :
  if 한개씩 == '역사':
    break # for문 탈출
  print(한개씩)

국어
수학


In [105]:
for 한개씩 in 과목 :
  if 한개씩 == '역사': # 역사를 꺼내고 아랫줄 수행
    continue # for문으로 돌아감
  print(한개씩)

국어
수학
영어


**while**

In [106]:
# 어떤 조건을 만족하면 무한히 반복처리.
숫자 = 0
while 숫자 < 10:
  숫자 = 숫자+1
  print(숫자)

1
2
3
4
5
6
7
8
9
10


In [107]:
# while문의 조건식이 틀리면 최종적으로 else문의 수행내용을 실행
숫자 = 0
while 숫자 < 10:
  print(숫자)
  숫자 = 숫자 +1
else : 
  print("끝")

0
1
2
3
4
5
6
7
8
9
끝


**함수**

In [108]:
# 내장함수
# list(), tuple(), dict()
# round() 반올림, abs() 절댓값

In [109]:
# 외장함수 -> import로 불러옴
import random

random.random() # 0~1사이 실수 중 임의의 값(난수)을 출력

0.41297885662972456

In [110]:
# 사용자정의함수
def 더하기 (숫자1,숫자2):
  print(숫자1+숫자2)

더하기(1,2)

3


In [111]:
def 제곱하기(숫자):
  print(숫자*숫자)

제곱하기(10)

100


In [112]:
임시 = 제곱하기(10)

100


In [113]:
임시 # 어떤 값도 저장되지 않음.

In [114]:
def 제곱(숫자):
  return(숫자*숫자)

제곱(2)

4

In [115]:
임시 = 제곱(2)

In [116]:
임시

4

**라이브러리 활용**

In [117]:
# 빅분기 실기에서 주로 사용되는 라이브러리
# pandas, numpy,sklearn

**pandas**

In [118]:
# 행과 열로 구성된 데이터 가공 목적
import pandas as pd

In [119]:
# 시리즈(series) : 1차원데이터.행(인덱스)와 데이터
# 데이터프레임(dataframe) : 2차원데이터 행(인덱스)과 열, 데이터

In [120]:
리스트변수 = ['홍길동','이순신','유관순','윤봉길']
시리즈변수 = pd.Series(리스트변수)

In [121]:
type(시리즈변수)

pandas.core.series.Series

In [122]:
시리즈변수

0    홍길동
1    이순신
2    유관순
3    윤봉길
dtype: object

In [123]:
리스트변수

['홍길동', '이순신', '유관순', '윤봉길']

In [124]:
리스트변수 = (['홍길동',29,'남'],['이순신',30,'남'],
         ['유관순',25,'여'],['윤봉길',35,'남'])
리스트변수

(['홍길동', 29, '남'], ['이순신', 30, '남'], ['유관순', 25, '여'], ['윤봉길', 35, '남'])

In [125]:
데이터프레임변수 = pd.DataFrame(리스트변수)
데이터프레임변수

0   1  2
0  홍길동  29  남
1  이순신  30  남
2  유관순  25  여
3  윤봉길  35  남

In [126]:
type(데이터프레임변수)

pandas.core.frame.DataFrame

In [127]:
데이터프레임변수.index = ['1번','2번','3번','4번']
데이터프레임변수

0   1  2
1번  홍길동  29  남
2번  이순신  30  남
3번  유관순  25  여
4번  윤봉길  35  남

In [128]:
데이터프레임변수.columns = ['이름','나이','성별']
데이터프레임변수

이름  나이 성별
1번  홍길동  29  남
2번  이순신  30  남
3번  유관순  25  여
4번  윤봉길  35  남

In [129]:
# 일부 열 값 뽑기
데이터프레임변수['나이']

1번    29
2번    30
3번    25
4번    35
Name: 나이, dtype: int64

In [130]:
데이터프레임변수[['나이','성별']]

나이 성별
1번  29  남
2번  30  남
3번  25  여
4번  35  남

In [131]:
# 일부 행 값 추출
데이터프레임변수[1:3]  # 인덱스로 가져오기

이름  나이 성별
2번  이순신  30  남
3번  유관순  25  여

In [132]:
데이터프레임변수['2번':'3번']  # 행 이름으로 가져오기

이름  나이 성별
2번  이순신  30  남
3번  유관순  25  여

In [133]:
# 파일읽고 쓰기
# 먼저, 현재 디렉토리 확인
import os
os.getcwd()

'/content'

In [134]:
# 파일불러오기
data = pd.read_csv('sample_data/mnist_test.csv')
data.head()

7  0  0.1  0.2  0.3  0.4  ...  0.662  0.663  0.664  0.665  0.666  0.667
0  2  0    0    0    0    0  ...      0      0      0      0      0      0
1  1  0    0    0    0    0  ...      0      0      0      0      0      0
2  0  0    0    0    0    0  ...      0      0      0      0      0      0
3  4  0    0    0    0    0  ...      0      0      0      0      0      0
4  1  0    0    0    0    0  ...      0      0      0      0      0      0

[5 rows x 785 columns]

In [135]:
# csv파일로 저장
data.to_csv('sample_data/test1.csv')

**sklearn**

In [136]:
# 머신러닝을 수행하는 라이브러리
# from skleran.모듈 import 함수 : 사이킷런의모듈에서 함수가져오기

# ex) train_test_split함수를 가져오기
from sklearn.model_selection import train_test_split

# ex) 트리모듈에서 의사결정나무 가져오기
from sklearn.tree import DecisionTreeClassifier

**numpy**

In [137]:
# 수치연산을 수행하는 선형대수 라이브러리
import numpy as np

In [138]:
np.zeros((2,3)) # 2행3열 행렬을 만들때, 모두0으로 채우기

array([[0., 0., 0.],
       [0., 0., 0.]])

In [139]:
np.ones((2,3)) # 2행3열 행렬을 만들때, 모두1로 채우기

array([[1., 1., 1.],
       [1., 1., 1.]])

In [140]:
np.full((2,3),10) # 2행3열 행렬을 만들때, 모두 10으로 채우기

array([[10, 10, 10],
       [10, 10, 10]])

In [141]:
np.array(range(20)) # 0~20개 숫자 만들기

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [142]:
np.array(range(20)).reshape(4,5) # 0~20개 숫자로 4행5열 행렬만들기

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**내장함수**

In [143]:
import pandas as pd
import numpy as np

# '\'는 여러 줄에 작성하기 위한 기호
데이터 = {\
       '나이' : [20,23,49,38,32,29,25,30,32,26], \
       '성별' : ['남','여','남','여','여','여','여','여','남', np.nan] \
       }

In [144]:
데이터

{'나이': [20, 23, 49, 38, 32, 29, 25, 30, 32, 26],
 '성별': ['남', '여', '남', '여', '여', '여', '여', '여', '남', nan]}

In [145]:
데이터1 = pd.DataFrame(데이터)
데이터1

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [146]:
type(데이터1)

pandas.core.frame.DataFrame

In [147]:
# sum()
데이터1['나이'].sum()

304

In [148]:
sum(데이터1['나이'])

304

In [149]:
# max()
데이터1['나이'].max() # max(데이터1['나이'])

49

In [150]:
# min()
데이터1['나이'].min() # min(데이터1['나이'])

20

In [151]:
# mean()
데이터1['나이'].mean() 

30.4

In [152]:
# median() : 중위수
데이터1['나이'].median() 

29.5

In [153]:
# var() : 분산
데이터1['나이'].var()

69.15555555555557

In [154]:
# std() : 표준편차
데이터1['나이'].std()

8.315981935740094

In [155]:
# pow() : 거듭제곱
pow(데이터1['나이'],3) # 3제곱


0      8000
1     12167
2    117649
3     54872
4     32768
5     24389
6     15625
7     27000
8     32768
9     17576
Name: 나이, dtype: int64

In [156]:
# quantile() : 사분위수
데이터1.quantile(0.25) # 1분위수

나이    25.25
Name: 0.25, dtype: float64

In [157]:
데이터1.quantile(0.5) # 2분위수(중위값)

나이    29.5
Name: 0.5, dtype: float64

In [158]:
데이터1.quantile(0.75) # 3분위수

나이    32.0
Name: 0.75, dtype: float64

In [159]:
데이터1.quantile(1) # 4분위수

나이    49.0
Name: 1, dtype: float64

In [160]:
# round() : 반올림
데이터1['나이'] /7

0    2.857143
1    3.285714
2    7.000000
3    5.428571
4    4.571429
5    4.142857
6    3.571429
7    4.285714
8    4.571429
9    3.714286
Name: 나이, dtype: float64

In [161]:
round(데이터1['나이'] /7) # 소수점 첫째자리에서 반올림

0    3.0
1    3.0
2    7.0
3    5.0
4    5.0
5    4.0
6    4.0
7    4.0
8    5.0
9    4.0
Name: 나이, dtype: float64

In [162]:
round(데이터1['나이'] /7, 2) # 소수점 셋째자리에서 반올림

0    2.86
1    3.29
2    7.00
3    5.43
4    4.57
5    4.14
6    3.57
7    4.29
8    4.57
9    3.71
Name: 나이, dtype: float64

In [163]:
# 비슷한 올림함수 ceil(), 내림함수 floor() 등은 math모듈을 가져와야함.
# import math()

**데이터 탐색**

In [164]:
# shape : 데이터구조
데이터1.shape  # (행, 열)

(10, 2)

In [165]:
데이터1['나이'].shape

(10,)

In [166]:
# len() : 문자열을 넣으면 문자열의 길이, 리스트나 데이터프레임타입등을 넣으면 원소개수
len(데이터1)

10

In [167]:
len('123456789')

9

In [168]:
# len(123) # 숫자는 안됨!

In [169]:
#len(str(123))

In [170]:
str

str

In [171]:
# size : 변수안에 들어있는 값들의 개수 출력. 데이터의 양
데이터1.size # 10행*2열 = 20

20

In [172]:
# columns : 열 이름
데이터1.columns

Index(['나이', '성별'], dtype='object')

In [173]:
# index : 행 이름
데이터1.index # 0~9(10-1)까지 이고 간격은 1

RangeIndex(start=0, stop=10, step=1)

**데이터요약**

In [174]:
# value_counts() : 걊 개수
데이터1['성별'].value_counts()

여    6
남    3
Name: 성별, dtype: int64

In [175]:
# unique() :  유일 값들 확인
데이터1['성별'].unique()

array(['남', '여', nan], dtype=object)

In [176]:
# isnull() : null여부 확인
데이터1.isnull()

나이     성별
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False
7  False  False
8  False  False
9  False   True

In [177]:
데이터1['성별'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: 성별, dtype: bool

In [178]:
# count()
데이터1.count()

나이    10
성별     9
dtype: int64

In [179]:
'i am superman!'.count('a')

2

In [180]:
# info() : 정보조회
데이터1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   나이      10 non-null     int64 
 1   성별      9 non-null      object
dtypes: int64(1), object(1)
memory usage: 288.0+ bytes


In [181]:
# describe() : 데이터표현
데이터1.describe()

나이
count  10.000000
mean   30.400000
std     8.315982
min    20.000000
25%    25.250000
50%    29.500000
75%    32.000000
max    49.000000

**데이터 변형**

In [182]:
# transpose() : 열과 행 위치 바꿈
데이터1.transpose()

0   1   2   3   4   5   6   7   8    9
나이  20  23  49  38  32  29  25  30  32   26
성별   남   여   남   여   여   여   여   여   남  NaN

In [183]:
# 또 다른 방법
데이터1.T

0   1   2   3   4   5   6   7   8    9
나이  20  23  49  38  32  29  25  30  32   26
성별   남   여   남   여   여   여   여   여   남  NaN

In [184]:
# loc[행이름, 열이름] : 행/열 *이름*으로 데이터가져오기
# 행만 : 변수.loc[행이름]
# 열만 : 변수.loc[:, 열이름]
# 행/열 : 변수.loc[행이름, 열이름]
데이터 = 데이터1
데이터

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [185]:
데이터.loc[3]

나이    38
성별     여
Name: 3, dtype: object

In [186]:
데이터.loc[3:7]

나이 성별
3  38  여
4  32  여
5  29  여
6  25  여
7  30  여

In [187]:
데이터.loc[:,'성별']

0      남
1      여
2      남
3      여
4      여
5      여
6      여
7      여
8      남
9    NaN
Name: 성별, dtype: object

In [188]:
데이터.loc[3:7, '성별']

3    여
4    여
5    여
6    여
7    여
Name: 성별, dtype: object

In [189]:
데이터 ['성별'] == '남'

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: 성별, dtype: bool

In [190]:
데이터.loc[데이터['성별'] == '남'] # loc는 true에 해당하는 행의 값만 추출.

나이 성별
0  20  남
2  49  남
8  32  남

In [191]:
# iloc[행위치, 열위치] : 행/열의 *위치*로 데이터 값 가져오기
# 행만 : 변수.iloc[행위치]
# 열만 : 변수.iloc[:, 열위치]
# 행/열 : 변수.iloc[행위치, 열위치]
데이터.iloc[3]

나이    38
성별     여
Name: 3, dtype: object

In [192]:
데이터.iloc[4:8] # iloc함수는 지정한 끝위치의 직전값까지만 데이터를 가져옴

나이 성별
4  32  여
5  29  여
6  25  여
7  30  여

In [193]:
데이터.iloc[:,1]

0      남
1      여
2      남
3      여
4      여
5      여
6      여
7      여
8      남
9    NaN
Name: 성별, dtype: object

In [194]:
데이터.iloc[:,0:2]

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [195]:
데이터.iloc[2,1]

'남'

In [196]:
데이터.iloc[3:7,1]

3    여
4    여
5    여
6    여
Name: 성별, dtype: object

In [197]:
# sort_values() : 값정렬
데이터

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [198]:
데이터.sort_values('나이') # 오름차순 정렬

나이   성별
0  20    남
1  23    여
6  25    여
9  26  NaN
5  29    여
7  30    여
4  32    여
8  32    남
3  38    여
2  49    남

In [199]:
데이터.sort_values('나이',ascending=False)

나이   성별
2  49    남
3  38    여
4  32    여
8  32    남
7  30    여
5  29    여
9  26  NaN
6  25    여
1  23    여
0  20    남

In [200]:
데이터['나이'].sort_values(ascending=True)

0    20
1    23
6    25
9    26
5    29
7    30
4    32
8    32
3    38
2    49
Name: 나이, dtype: int64

In [201]:
데이터.sort_values(['나이','성별']) # 첫번째 열부터 정렬후 두번째 열 정렬

나이   성별
0  20    남
1  23    여
6  25    여
9  26  NaN
5  29    여
7  30    여
8  32    남
4  32    여
3  38    여
2  49    남

In [202]:
# filna() : 결측치 메꾸기
데이터['성별2'] = 데이터['성별'].fillna('남')
데이터

나이   성별 성별2
0  20    남   남
1  23    여   여
2  49    남   남
3  38    여   여
4  32    여   여
5  29    여   여
6  25    여   여
7  30    여   여
8  32    남   남
9  26  NaN   남

In [204]:
# dropna() : 결측치 삭제
데이터 = 데이터.dropna()
데이터

나이 성별 성별2
0  20  남   남
1  23  여   여
2  49  남   남
3  38  여   여
4  32  여   여
5  29  여   여
6  25  여   여
7  30  여   여
8  32  남   남

In [205]:
# drop() : 행/열 제거
# 행삭제 : 변수.drop(index = [행이름1. 행이름2,,,,])
# 열삭제 ; 변수.drop(columns = [열이름1,열이름2,,,])
데이터.drop(index = [0,2,4,6,8])

나이 성별 성별2
1  23  여   여
3  38  여   여
5  29  여   여
7  30  여   여

In [206]:
데이터.drop(columns = ['성별'])

나이 성별2
0  20   남
1  23   여
2  49   남
3  38   여
4  32   여
5  29   여
6  25   여
7  30   여
8  32   남

In [207]:
# replace(현재값, 교체값) : 값 바꿈
데이터['성별2'] = 데이터['성별'].replace('여','F').replace('남','M')
데이터

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


나이 성별 성별2
0  20  남   M
1  23  여   F
2  49  남   M
3  38  여   F
4  32  여   F
5  29  여   F
6  25  여   F
7  30  여   F
8  32  남   M