In [1]:
import numpy as np

#### 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능

 * 1차원 벡터 인덱싱

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
x[3]

3

In [5]:
x[3] = 100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


* 2차원 행렬 인덱싱

In [6]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
x[0] 

array([0, 1, 2, 3, 4])

In [12]:
x[0,2]

2

In [13]:
x[1,-1] # 마지막

9

* 3차원 텐서 인덱싱

In [14]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [16]:
x[1,2]

array([18, 19, 20])

In [17]:
x[1,2,-1]

20

#### 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능

* 1차원 벡터 슬라이싱

In [19]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [21]:
x[:7]

array([0, 1, 2, 3, 4, 5, 6])

* 2차원 행렬 슬라이싱

In [22]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
x[:,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [25]:
x[0,:2] # 벡터, 차원이 하나 줄어듦

array([0, 1])

In [26]:
x[:1,:2] # 행렬, 차원 유지

array([[0, 1]])

* 3차원 텐서 슬라이싱

In [27]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [28]:
x[:1,:2,:]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [29]:
x[0,:2,:]

array([[0, 1, 2],
       [3, 4, 5]])