### linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [3]:
# 정방행렬만 가능
x = np.random.rand(3,3) 
print(x)

# 역행렬
# x @ np.linalg.inv(x)
np.matmul(x, np.linalg.inv(x))

[[0.61891882 0.6076351  0.17407187]
 [0.65505111 0.60322779 0.32391503]
 [0.73624353 0.76454016 0.35715861]]


array([[ 1.00000000e+00,  7.21771909e-17, -1.03450633e-15],
       [ 3.66936434e-16,  1.00000000e+00, -1.41358276e-15],
       [-9.85108184e-17, -4.36228248e-16,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [4]:
A = np.array([[1,1],[2,4]])
B = np.array([25,64])

# 연립방정식 해 풀기
x = np.linalg.solve(A,B)
print(x)

[18.  7.]


In [9]:
# 제대로 풀었는지 확인
# np.allclose(A@x,B) 
np.allclose(np.dot(A,x), B)

True