In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.95467817 0.0516019  0.53279679 0.71032398 0.22476847]
 [0.9738968  0.66464246 0.71245631 0.81837626 0.59695789]
 [0.90106902 0.98120074 0.93734103 0.81286876 0.6354823 ]]


#### 연산 함수
 - add, substract, multiply, divide

In [3]:
np.add(x,y) # 두 개의 shape이 같아야함. 

array([[ 0.95467817,  1.0516019 ,  2.53279679,  3.71032398,  4.22476847],
       [ 5.9738968 ,  6.66464246,  7.71245631,  8.81837626,  9.59695789],
       [10.90106902, 11.98120074, 12.93734103, 13.81286876, 14.6354823 ]])

In [5]:
x + y

array([[ 0.95467817,  1.0516019 ,  2.53279679,  3.71032398,  4.22476847],
       [ 5.9738968 ,  6.66464246,  7.71245631,  8.81837626,  9.59695789],
       [10.90106902, 11.98120074, 12.93734103, 13.81286876, 14.6354823 ]])

In [4]:
np.subtract(x,y)

array([[-0.95467817,  0.9483981 ,  1.46720321,  2.28967602,  3.77523153],
       [ 4.0261032 ,  5.33535754,  6.28754369,  7.18162374,  8.40304211],
       [ 9.09893098, 10.01879926, 11.06265897, 12.18713124, 13.3645177 ]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [6]:
print(y)

[[0.95467817 0.0516019  0.53279679 0.71032398 0.22476847]
 [0.9738968  0.66464246 0.71245631 0.81837626 0.59695789]
 [0.90106902 0.98120074 0.93734103 0.81286876 0.6354823 ]]


In [7]:
y.mean() # np.mean(y)

0.7005640589154325

In [8]:
np.max(y)

0.9812007405010233

In [9]:
np.argmax(y) # 최대값 해당 인덱스 
# argmin - 최소값

11

In [12]:
print(np.var(y)) # 분산
print(np.median(y))# 중앙값
print(np.std(y)) # 표준편차

0.06886503032079361
0.7124563079535358
0.2624214745800991


#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [13]:
np.sum(y)

10.508460883731487

In [14]:
np.cumsum(y) # 누적 합

array([ 0.95467817,  1.00628007,  1.53907686,  2.24940084,  2.47416931,
        3.44806611,  4.11270858,  4.82516488,  5.64354114,  6.24049904,
        7.14156806,  8.1227688 ,  9.06010983,  9.87297858, 10.50846088])

In [21]:
print(np.sum(y, axis = 0)) #sum(y)
print('-----------------')
print(np.sum(y, axis = None))

[2.82964399 1.6974451  2.18259413 2.341569   1.45720866]
-----------------
10.508460883731487


#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [22]:
z = np.random.randn(10)
print(z)

[ 1.55590207 -1.41944237 -1.81558694  1.05300991 -1.17533382 -2.028565
  0.75680492  1.05488487  2.1063222  -1.64104737]


In [23]:
z>0

array([ True, False, False,  True, False, False,  True,  True,  True,
       False])

In [24]:
np.any(z>0) # 1개라도 참이면 T

True

In [26]:
print(np.all(z>0)) # 모두 참이면 T
print(np.all(z!=0))

False
True


#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [27]:
z = np.random.randn(10)
print(z)

[ 0.95236326 -0.04380834 -2.04482727 -0.5798261   1.52217859  0.25381043
  0.23586642 -0.32422918  0.57656111 -0.45710811]


In [28]:
np.where(z>0, z, 0) # 조건, 참, 거짓

array([0.95236326, 0.        , 0.        , 0.        , 1.52217859,
       0.25381043, 0.23586642, 0.        , 0.57656111, 0.        ])