In [11]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [12]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.98465582 0.86587556 0.49804893 0.49587552 0.6080316 ]
 [0.4279563  0.11759225 0.8493371  0.29395828 0.89447789]
 [0.35190846 0.42337884 0.84201559 0.31521087 0.64117096]]


* Scalar(상수)와의 연산

In [13]:
x+y

array([[ 0.98465582,  1.86587556,  2.49804893,  3.49587552,  4.6080316 ],
       [ 5.4279563 ,  6.11759225,  7.8493371 ,  8.29395828,  9.89447789],
       [10.35190846, 11.42337884, 12.84201559, 13.31521087, 14.64117096]])

In [14]:
#x +2
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [23]:
a = np.arange(12).reshape(4,3)
b = np.arange(100,103)
c = np.arange(1000,1004)
d = b.reshape(1,3)

print(a)
print(a.shape)
print(b)
print(b.shape)
print(c)
print(c.shape)
print(d)
print(d.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[100 101 102]
(3,)
[1000 1001 1002 1003]
(4,)
[[100 101 102]]
(1, 3)


In [19]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [26]:
# a+c # 오류

In [25]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])