In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [3]:
np.random.rand(2,3) # 0~1 사이 랜덤값

array([[0.24232412, 0.33218989, 0.12355941],
       [0.93591508, 0.59145207, 0.64355164]])

In [4]:
np.random.rand(2,3,4)

array([[[2.93382340e-01, 5.54474289e-02, 1.36573687e-01, 2.70008070e-01],
        [2.93710542e-01, 5.95583110e-01, 9.75914223e-01, 2.26874516e-02],
        [8.07185754e-01, 3.14777051e-01, 5.23172411e-01, 5.60855173e-01]],

       [[3.72416689e-04, 4.49870886e-01, 9.25052024e-02, 8.58663617e-02],
        [4.62435447e-01, 3.58110993e-01, 4.95737681e-01, 4.99010514e-01],
        [9.45257820e-01, 2.41200765e-01, 9.66413518e-01, 7.48502388e-01]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [5]:
np.random.randn(3,4)

array([[-1.05794032,  0.11639501,  0.68506824, -0.19329598],
       [-1.00828949,  1.06620848, -1.63066374, -0.93783553],
       [-0.22967264,  0.09446942,  0.59237589, -1.56378302]])

In [6]:
np.random.randn(3,4,2)

array([[[-0.30725081, -1.23704442],
        [-2.17135941, -0.90026569],
        [ 0.5416354 , -1.33084812],
        [ 1.49111668, -1.89751868]],

       [[ 0.00923403, -0.91900406],
        [-0.10689813, -1.47825126],
        [-0.41794267, -0.67814633],
        [-1.0433914 ,  0.81630372]],

       [[-1.62908801, -0.22025976],
        [ 0.36813477,  0.08356658],
        [ 0.98469395,  1.40307118],
        [-0.42422155, -0.38591593]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [8]:
np.random.randint(1,100,size =(3,5))

array([[ 9, 86, 56,  9, 75],
       [50, 24, 14, 34,  3],
       [33, 61, 41, 50, 81]])

In [9]:
np.random.randint(1,100,size =(5,))

array([22, 61, 75, 11, 60])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [12]:
np.random.seed(100)
np.random.randn(3,4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [14]:
np.random.choice(100, size = (3, 4))

array([[71, 80,  2, 94],
       [19, 98, 63, 53],
       [27, 56, 30, 48]])

In [17]:
x = np.array([1,2,3,1.5,2.6,4.7])
np.random.choice(x,size=(2,2)) # 중복 허용

array([[1. , 3. ],
       [4.7, 3. ]])

In [18]:
x = np.array([1,2,3,1.5,2.6,4.7])
np.random.choice(x,size=(2,2), replace = False) # 중복 불가

array([[1.5, 2.6],
       [3. , 4.7]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [19]:
np.random.uniform(1.0, 3.0, size = (4,5))

array([[1.35164262, 1.23660567, 2.72589134, 1.14973376, 2.65018972],
       [2.67226363, 1.15078982, 1.02280158, 1.09684114, 1.71424542],
       [2.33138675, 1.02277922, 1.21583553, 2.8020262 , 2.58975752],
       [2.62292196, 2.28055611, 2.24955902, 1.29101502, 2.1404318 ]])

In [20]:
np.random.normal(size = (3,4))
#np.random.randn(3,4)

array([[-0.18499993, -0.43118745,  0.14253625, -1.49639345],
       [ 0.30687456, -0.04634723,  0.41714428, -0.60377052],
       [ 0.68596725,  0.85997379,  0.19155544,  1.17822793]])