In [1]:
import numpy as np

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [3]:
x = np.random.randint(1,100,size=10)
print(x)

[79 22 76 40 19 29 59 33 42 35]


In [6]:
even_mask = x % 2 == 0
print(even_mask)

[False  True  True  True False False False False  True False]


- bool 리스트를 인덱스로 전달

In [8]:
x[even_mask] # T의 값만 가져옴

array([22, 76, 40, 42])

In [11]:
x[x % 2 == 0]

array([22, 76, 40, 42])

In [12]:
x[x>30]

array([79, 76, 40, 59, 33, 42, 35])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [13]:
# x % 2 == 0 , x<30

# and
x[(x%2==0) & (x<30)] 

array([22])

In [14]:
# or 
x[(x<30) | (x>50)]

array([79, 22, 76, 19, 29, 59])

#### 예제) 2019년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [15]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [17]:
# 평균기온이 25도 넘는 날의 수 
# len(temp[temp>25.0])
np.sum(temp>25.0) # True는 1

21

In [18]:
# 평균기온이 25도를 넘는 날의 평균기온
np.mean(temp[temp>25.0])

26.857142857142858